### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by chiefjazzdiewltr** [chiefjazzdiewltr/GraphicCalculator#1]
### Current Goals
- [ ] Finish the table view
- [ ] Finish the main command line interface
- [ ] Finish the processor for polynomial functions
### Long Term Goals
- [ ] Add a GUI interface
- [ ] Add support for an actual graph
- [ ] Support a wider range of functions
